sonar.projectKey=bhavesh-bhatt-tech_skillsync
sonar.organization=bhavesh-bhatt-tech
sonar.projectName=SkillSync
sonar.sourceEncoding=UTF-8

sonar.sources=src,server,prisma
sonar.tests=tests,src
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx,tests/**/*.spec.ts,tests/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.exclusions=**/node_modules/**,dist/**,coverage/**,.storybook/**
sonar.coverage.exclusions=server/**,prisma/**,src/main.tsx,src/vite-env.d.ts,src/**/*.stories.tsx,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
